---
title: "Data Mining- Titanic dataset"
output: html_notebook
---

```{r}
library(rpart)
install.packages('rattle')
install.packages('rpart.plot')
install.packages('RColorBrewer')
library(rattle)
library(rpart.plot)
library(RColorBrewer)
install.packages('e1071')
library(e1071)
install.packages('caret')
library(caret)
install.packages('naivebayes')
library(naivebayes)
install.packages("DMwR")
library(DMwR)
install.packages("keras")
library(keras)
```


## **Decision tree**

## On raw data
***
```{r}
train = read.csv("train.csv", header=T)
summary(data_source)

fit <- rpart(Survived ~ Pclass + Sex + Age + SibSp + Parch + Fare + Embarked,
               data=train,
               method="class")
plot(fit)
text(fit)

```


```{r}
fancyRpartPlot(fit)

```

## Preprocessed data
***
```{r}
load_data = function() {
  data_source = data.frame(read.csv("train.csv", header = T))
  library(varhandle)
  data_source$Sex = unfactor(data_source$Sex)
  data_source$Embarked = unfactor(data_source$Embarked)
  # Fill in missing age entries with average, embarked with Southampton
  for (i in 1:length(data_source$Age)) {
    if (is.na(data_source$Age[i])) {
      data_source$Age[i] = mean(data_source$Age, na.rm = TRUE)
    }
    
    if (data_source$Embarked[i] == "" ||
      data_source$Embarked[i] == "S") {
      data_source$Embarked[i] = 3
    }
    
    else if (data_source$Embarked[i] == "C") {
      data_source$Embarked[i] = 1
    }
    else if (data_source$Embarked[i] == "Q") {
      data_source$Embarked[i] = 2
    }
    
    if (data_source$Sex[i] == "male") {
      data_source$Sex[i] = 2
    }
    else if (data_source$Sex[i] == "female") {
      data_source$Sex[i] = 1
    }
  }
  data_source$Embarked = as.numeric(data_source$Embarked)
  data_source$Sex = as.numeric(data_source$Sex)
  
  data_source$Survived = as.factor(data_source$Survived)
  data_source$Pclass = as.factor(data_source$Pclass)
  data_source$Sex = as.factor(data_source$Sex)
  data_source$Embarked = as.factor(data_source$Embarked)
  levels(data_source$Embarked) = c("Southampton", "Cherbourg", "Queenstown", "Southampton")
  levels(data_source$Sex) = c("Female", "Male")
  levels(data_source$Survived) = c("No", "Yes")
  
  data_source$Family = data_source$Parch + data_source$SibSp
  data_source$SibSp = as.integer(data_source$SibSp)
  data_source$Parch = as.integer(data_source$Parch)
  data_source$Family = as.integer(data_source$Family)
  return(data_source)
}

train = load_data()

fit = rpart(Survived ~ Pclass + Sex + Age + Family + Fare + Embarked,
               data=train,
               method="class")
fancyRpartPlot(fit)
```


## Prediction
***
```{r}
#print(fit)
#printcp(fit)
#plotcp(fit)
prediction = predict(fit, train, type = "class")


accuracies = c()
precisions = c()
recalls = c()
train_dt = load_data()
train_dt$Name = NULL
train_dt$Ticket = NULL
train_dt$Cabin = NULL
train_dt$PassengerId = NULL
train_dt$SibSp = NULL
train_dt$Parch = NULL
train_dt = SMOTE(Survived~., train_dt, perc.over=200, perc.under=120)
folds = createFolds(train_dt$Survived, k = 5, list = TRUE, returnTrain = TRUE)
avg_confusion_matrix = NULL
for (fold in folds) {
  train_data = train_dt[fold,]
  test_data = train_dt[-fold,]
  fit = rpart(Survived ~ .,
               data = train_data,
               method = "class")
  prediction = predict(object = fit, newdata = test_data, type = "class")
  confusion_matrix = confusionMatrix(prediction, as.factor(train_dt[-fold, ]$Survived))
  if (is.null(avg_confusion_matrix)) {
    avg_confusion_matrix = confusion_matrix
  } else {
    avg_confusion_matrix$table = avg_confusion_matrix$table + confusion_matrix$table
  }
  accuracy = (confusion_matrix$table[1,1] + confusion_matrix$table[2,2]) / sum(confusion_matrix$table)
  accuracies = c(accuracies, accuracy)
  precision_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[,1])
  precision_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[,2])
  precisions = c(precisions, mean(c(precision_yes, precision_no)))
  recall_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[1,])
  recall_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[2,])
  recalls = c(recalls, mean(c(recall_yes, recall_no)))
}

precision_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[,1])
precision_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[,2])
recall_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[1,])
recall_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[2,])
cat("Accuracy (mean):",mean(accuracies),"\nPrecision (mean):", mean(precisions), "\nRecall (mean):",mean(recalls),"\n")
print(avg_confusion_matrix$table/5)
cat("Precision:\n\tYes:", precision_yes,"\n\tNo:",precision_no,"\nRecall:\n\tYes:", recall_yes,"\n\tNo:",recall_no,"\n")
```


## **Naive Bayes**

```{r}
train_nb = load_data()
train_nb$Name = NULL
train_nb$Fare = NULL
train_nb$Family = NULL
train_nb$SibSp = NULL
train_nb$Parch = NULL
train_nb$Age = NULL

train_nb$Ticket = NULL
train_nb$Cabin = NULL
train_nb$PassengerId = NULL
train_nb = SMOTE(Survived~., train_nb, perc.over=200, perc.under=120)

accuracies = c()
precisions = c()
recalls = c()
avg_confusion_matrix=NULL
folds = createFolds(train_nb$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (fold in folds) {
  train_data = train_nb[fold,]
  test_data = train_nb[-fold,]
  fit = naiveBayes(Survived~.,usekernel=F, data=train_data)
  prediction = suppressWarnings(predict(fit, newdata = test_data, type = "class"))
  confusion_matrix = confusionMatrix(prediction, as.factor(train_nb[-fold, ]$Survived))
  if (is.null(avg_confusion_matrix)) {
    avg_confusion_matrix = confusion_matrix
  } else {
    avg_confusion_matrix$table = avg_confusion_matrix$table + confusion_matrix$table
  }
  accuracy = (confusion_matrix$table[1,1] + confusion_matrix$table[2,2]) / sum(confusion_matrix$table)
  accuracies = c(accuracies, accuracy)
  precision_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[,1])
  precision_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[,2])
  precisions = c(precisions, mean(c(precision_yes, precision_no)))
  recall_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[1,])
  recall_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[2,])
  recalls = c(recalls, mean(c(recall_yes, recall_no)))
}
precision_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[,1])
precision_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[,2])
recall_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[1,])
recall_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[2,])
cat("Accuracy (mean):",mean(accuracies),"\nPrecision (mean):", mean(precisions), "\nRecall (mean):",mean(recalls),"\n")
print(avg_confusion_matrix$table/5)
cat("Precision:\n\tYes:", precision_yes,"\n\tNo:",precision_no,"\nRecall:\n\tYes:", recall_yes,"\n\tNo:",recall_no,"\n")
```
## **kNN**
```{r}
train_knn = load_data()
train_knn$Name = NULL
train_knn$Ticket = NULL
train_knn$PassengerId=NULL
train_knn$Cabin=NULL
train_knn$Embarked=NULL
train_knn$Pclass=NULL
train_knn$Sex=NULL
train_knn = SMOTE(Survived~., train_knn, perc.over=200, perc.under=120)

accuracies = c()
precisions = c()
recalls = c()
avg_confusion_matrix = NULL
folds = createFolds(train_knn$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (fold in folds) {
  train_data = train_knn[fold,]
  test_data = train_knn[-fold,]
  prediction = kNN(Survived~., train_data,test_data,norm=T, k=13)
  confusion_matrix = confusionMatrix(prediction, as.factor(train_knn[-fold, ]$Survived))
  if (is.null(avg_confusion_matrix)) {
    avg_confusion_matrix = confusion_matrix
  } else {
    avg_confusion_matrix$table = avg_confusion_matrix$table + confusion_matrix$table
  }
  accuracy = (confusion_matrix$table[1,1] + confusion_matrix$table[2,2]) / sum(confusion_matrix$table)
  accuracies = c(accuracies, accuracy)
  precision_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[,1])
  precision_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[,2])
  precisions = c(precisions, mean(c(precision_yes, precision_no)))
  recall_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[1,])
  recall_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[2,])
  recalls = c(recalls, mean(c(recall_yes, recall_no)))
}

precision_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[,1])
precision_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[,2])
recall_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[1,])
recall_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[2,])
cat("Accuracy (mean):",mean(accuracies),"\nPrecision (mean):", mean(precisions), "\nRecall (mean):",mean(recalls),"\n")
print(avg_confusion_matrix$table/5)
cat("Precision:\n\tYes:", precision_yes,"\n\tNo:",precision_no,"\nRecall:\n\tYes:", recall_yes,"\n\tNo:",recall_no,"\n")
```

## **Neural Network**
```{r}
train_nn = load_data()
train_nn$Name = NULL
train_nn$Ticket = NULL
train_nn$PassengerId=NULL
train_nn$Cabin=NULL
train_nn$Embarked=NULL
train_nn$Pclass=NULL
train_nn$Sex=NULL
train_nn = SMOTE(Survived~., train_nn, perc.over=200, perc.under=120)

accuracies = c()
precisions = c()
recalls = c()
avg_confusion_matrix = NULL
folds = createFolds(train_nn$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (fold in folds) {
  train_data = train_nn[fold,]
  test_data = train_nn[-fold,]
  trainingNN_y = train_data$Survived
  trainingNN_x = train_data[ , !(names(train_data) %in% c("Survived"))]
  
  testingNN_y = test_data$Survived
  testingNN_x = test_data[ , !(names(test_data) %in% c("Survived"))]
  
  
  model <- keras_model_sequential() 
  model %>% 
    layer_dense(units = 24, activation = 'relu', input_shape = c(5)) %>% 
    #layer_dropout(rate = 0.4) %>%
    #layer_dense(units = 6, activation = 'relu') %>%
    #layer_dropout(rate = 0.3) %>%
    layer_dense(units = 1, activation = 'softmax')

summary(model)

model %>% compile(
    loss = 'binary_crossentropy', #binary_crossentropy, categorical_crossentropy
    optimizer = optimizer_rmsprop(), #'adam', optimizer_rmsprop()
    metrics = c('accuracy')
)
history <- model %>% fit(
    as.matrix(trainingNN_x), as.matrix(trainingNN_y), 
    epochs = 100, batch_size = 10 #best combination, 100/10
)
plot(history)
model %>% evaluate(testingNN_x, testingNN_y)

prediction = model %>% predict_classes(testingNN_x)

  
  
  confusion_matrix = confusionMatrix(prediction, as.factor(train_nn[-fold, ]$Survived))
  if (is.null(avg_confusion_matrix)) {
    avg_confusion_matrix = confusion_matrix
  } else {
    avg_confusion_matrix$table = avg_confusion_matrix$table + confusion_matrix$table
  }
  accuracy = (confusion_matrix$table[1,1] + confusion_matrix$table[2,2]) / sum(confusion_matrix$table)
  accuracies = c(accuracies, accuracy)
  precision_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[,1])
  precision_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[,2])
  precisions = c(precisions, mean(c(precision_yes, precision_no)))
  recall_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[1,])
  recall_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[2,])
  recalls = c(recalls, mean(c(recall_yes, recall_no)))
}


# --------------------------------- prediction for test matrix
test_matrix <- as.matrix(select(test_imputed, -(PassengerId)))
predNN <- model %>% predict_classes(test_matrix)
```


## **SVM**

```{r}
train_svm = load_data()
train_svm$Name = NULL
train_svm$Ticket = NULL
train_svm$PassengerId=NULL
train_svm$Cabin=NULL
train_svm$Embarked=NULL
train_svm$Pclass=NULL
train_svm$Sex=NULL
train_svm = SMOTE(Survived~., train_svm, perc.over=200, perc.under=120)

accuracies = c()
precisions = c()
recalls = c()
avg_confusion_matrix = NULL
folds = createFolds(train_svm$Survived, k = 5, list = TRUE, returnTrain = TRUE)
for (fold in folds) {
  train_data = train_svm[fold,]
  test_data = train_svm[-fold,]
  fit = svm(Survived~., train_data, scale=T, kernel="radial")
  prediction = predict(fit, newdata = test_data, type = "class")
  confusion_matrix = confusionMatrix(prediction, as.factor(train_svm[-fold, ]$Survived))
  if (is.null(avg_confusion_matrix)) {
    avg_confusion_matrix = confusion_matrix
  } else {
    avg_confusion_matrix$table = avg_confusion_matrix$table + confusion_matrix$table
  }
  accuracy = (confusion_matrix$table[1,1] + confusion_matrix$table[2,2]) / sum(confusion_matrix$table)
  accuracies = c(accuracies, accuracy)
  precision_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[,1])
  precision_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[,2])
  precisions = c(precisions, mean(c(precision_yes, precision_no)))
  recall_no = confusion_matrix$table[1,1] / sum(confusion_matrix$table[1,])
  recall_yes = confusion_matrix$table[2,2] / sum(confusion_matrix$table[2,])
  recalls = c(recalls, mean(c(recall_yes, recall_no)))
}

precision_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[,1])
precision_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[,2])
recall_no = avg_confusion_matrix$table[1,1] / sum(avg_confusion_matrix$table[1,])
recall_yes = avg_confusion_matrix$table[2,2] / sum(avg_confusion_matrix$table[2,])
cat("Accuracy (mean):",mean(accuracies),"\nPrecision (mean):", mean(precisions), "\nRecall (mean):",mean(recalls),"\n")
print(avg_confusion_matrix$table/5)
cat("Precision:\n\tYes:", precision_yes,"\n\tNo:",precision_no,"\nRecall:\n\tYes:", recall_yes,"\n\tNo:",recall_no,"\n")
```











































