---
title: "Data Mining- Titanic dataset"
output: html_notebook
---


Install dependencies
```{r}
install.packages("devtools")
library(devtools)
install.packages("PerformanceAnalytics", dependencies=TRUE)
install_github("vqv/ggbiplot")
install.packages("Rtsne")
install.packages("varhdanle")
library("PerformanceAnalytics")
library(ggbiplot)
library("Rtsne")
library(varhandle)
```

## 1. **Univariate analysis**


```{r}
data_source = data.frame(read.csv("train.csv", header=T))
summary(data_source)
data_source$Sex = unfactor(data_source$Sex)
data_source$Embarked = unfactor(data_source$Embarked)
# Fill in missing age entries with average, embarked with Southampton
for (i in 1:length(data_source$Age)){
  if(is.na(data_source$Age[i])) {
    data_source$Age[i] = mean(data_source$Age, na.rm=TRUE)
  }
  
  if(data_source$Embarked[i] == "" || data_source$Embarked[i] == "S") {
    data_source$Embarked[i] = 3
  }
  else if (data_source$Embarked[i] == "C") {
    data_source$Embarked[i] = 1
  }
  else if(data_source$Embarked[i] == "Q") {
    data_source$Embarked[i] = 2
  }
  
  if(data_source$Sex[i] == "male") {
    data_source$Sex[i] = 2
  } 
  else if(data_source$Sex[i] == "female") {
    data_source$Sex[i] = 1
  }
  
}
data_source$Embarked = as.numeric(data_source$Embarked)
data_source$Sex = as.numeric(data_source$Sex)
```

## Numeric variables distribution
***

### Age

```{r}
hist(data_source$Age, xlab="Age", main="Age distribution", labels=TRUE, ylim = c(0,300), col = "grey")

```
### Fare

```{r}
hist(data_source$Fare, xlab="Fare", main="Fare distribution", labels=TRUE, ylim = c(0,1000), col = "grey")
```

###Siblings number

```{r}
hist_sib = hist(data_source$SibSp, xlab="Siblings number", main="Siblings number distribution", labels=TRUE, ylim = c(0,1000), col = "grey")


```

## Categorical variables distribution
***

### Ticket class


```{r}
class_frequency = table(data_source$Pclass)
bar = barplot(class_frequency, xlab="Ticket class", ylab="Frequency", ylim=c(0, 500))
text(x = bar, y = class_frequency , label = class_frequency, pos = 1)
```

### Sex
```{r}
sex_frequency = table(data_source$Sex)
bar = barplot(sex_frequency, xlab="Sex", ylab="Frequency")
text(x = bar, y = sex_frequency , label = sex_frequency, pos = 1)
```

### Embarkation place

```{r}
place_frequency = table(data_source$Embarked)
names(place_frequency) = c('Uknown', 'Cherbourg', 'Queenstown', 'Southampton')
bar = barplot(place_frequency, xlab="Embarkation place", ylab="Frequency", ylim = c(0,700), main="Places of embarkation distribution")
text(x = bar, y = place_frequency , label = place_frequency, pos = 3)
```
## 2. **Bivariate analysis**


## 3. **Multivariate analysis**

```{r}
my_data <- data_source[, c(3,5,6,7,8,10,12)]
chart.Correlation(my_data, histogram=TRUE, pch=19, method=c("pearson"))
```

##Principal Component Analysis

```{r}
pca = prcomp(~ ., data=data_source[, c(3,5,6,7,8,10,12)], center = TRUE,scale. = TRUE, na.action=na.omit)
summary(pca)
ggbiplot(pca)
plot(pca)
```
##t-SNE

```{r}
tsne <- Rtsne(data_source, check_duplicates = FALSE, theta=0.5, dims=2, perplexity=70, max_iter=3000, early_exag_coeff=12, stop_lying_iter=1200)
plot(tsne$Y, t='n', main="t-SNE")
cols <- c("red", "green")
text(tsne$Y, labels=data_source[,2], col=cols[data_source[,2]+1])
```

