---
title: "R Notebook"
output: html_notebook
---
```{r}
data_source = data.frame(read.csv("train.csv", header=T))
summary(data_source)

library(varhandle)
data_source$Sex = unfactor(data_source$Sex)
data_source$Embarked = unfactor(data_source$Embarked)
# Fill in missing age entries with average, embarked with Southampton
for (i in 1:length(data_source$Age)){
  if(is.na(data_source$Age[i])) {
    data_source$Age[i] = mean(data_source$Age, na.rm=TRUE)
  }
  
  if(data_source$Embarked[i] == "" || data_source$Embarked[i] == "S") {
    data_source$Embarked[i] = 3
  }
  else if (data_source$Embarked[i] == "C") {
    data_source$Embarked[i] = 1
  }
  else if(data_source$Embarked[i] == "Q") {
    data_source$Embarked[i] = 2
  }
  
  if(data_source$Sex[i] == "male") {
    data_source$Sex[i] = 2
  } 
  else if(data_source$Sex[i] == "female") {
    data_source$Sex[i] = 1
  }
  
}
data_source$Embarked = as.numeric(data_source$Embarked)
data_source$Sex = as.numeric(data_source$Sex)
```
### General rules
```{r}
data_source$Survived = as.factor(as.character(data_source$Survived))

data_source$SibSp = cut(data_source$SibSp, breaks = c(-Inf, 0, Inf), labels = c('No', 'Yes'), right = FALSE)
data_source$Parch = cut(data_source$Parch, breaks = c(-Inf, 0, Inf), labels = c('No', 'Yes'), right = FALSE)
data_source$Fare = cut(data_source$Age, breaks = c(-Inf, 5, 10, 15, Inf), labels = c('0-5', '5-10', '10-15', '15+'), right = FALSE)
data_source$Pclass = as.factor(data_source$Pclass)
data_source$Sex = as.factor(data_source$Sex)
data_source$Age = cut(data_source$Age, breaks = c(-Inf, 18, Inf), labels = c('Child', 'Adult'), right = FALSE)
data_source$Embarked = as.factor(data_source$Embarked)
levels(data_source$Embarked)=c("Southampton","Cherbourg", "Queenstown", "Southampton")
levels(data_source$Sex)=c("Female","Male")
levels(data_source$Survived)=c("No","Yes")
rule = apriori(data_source[,c(2:10,12)], 
                parameter=list(minlen=2, supp=0.5, conf=0.7),  
                appearance = list(default="both"))
sort.rule = sort(rule, by="confidence")
inspect(sort.rule)
```
### Survival rules
```{r}
rule = apriori(data_source[,c(2:10,12)], 
                parameter=list(minlen=2, supp=0.2, conf=0.7),  
                appearance = list(default="lhs", rhs=c("Survived=No", "Survived=Yes")))
sort.rule = sort(rule, by="confidence")
inspect(sort.rule)
plot(sort.rule)
plot(sort.rule, method="graph",
     control=list(nodeCol="red", edgeCol="blue", type="items"))
```

































