---
title: "R Notebook"
output: html_notebook
---
### Environment setup
```{r}
install.packages("ISLR")
install.packages("tree")
library(ISLR)
require(tree)

load_data = function() {
  data_source = data.frame(read.csv("train.csv", header = T))
  library(varhandle)
  data_source$Sex = unfactor(data_source$Sex)
  data_source$Embarked = unfactor(data_source$Embarked)
  # Fill in missing age entries with average, embarked with Southampton
  for (i in 1:length(data_source$Age)) {
    if (is.na(data_source$Age[i])) {
      data_source$Age[i] = mean(data_source$Age, na.rm = TRUE)
    }
    
    if (data_source$Embarked[i] == "" ||
      data_source$Embarked[i] == "S") {
      data_source$Embarked[i] = 3
    }
    
    else if (data_source$Embarked[i] == "C") {
      data_source$Embarked[i] = 1
    }
    else if (data_source$Embarked[i] == "Q") {
      data_source$Embarked[i] = 2
    }
    
    if (data_source$Sex[i] == "male") {
      data_source$Sex[i] = 2
    }
    else if (data_source$Sex[i] == "female") {
      data_source$Sex[i] = 1
    }
  }
  data_source$Embarked = as.numeric(data_source$Embarked)
  data_source$Sex = as.numeric(data_source$Sex)
  
  data_source$Survived = as.factor(data_source$Survived)
  data_source$Pclass = as.factor(data_source$Pclass)
  data_source$Sex = as.factor(data_source$Sex)
  data_source$Embarked = as.factor(data_source$Embarked)
  levels(data_source$Embarked) = c("Southampton", "Cherbourg", "Queenstown", "Southampton")
  levels(data_source$Sex) = c("Female", "Male")
  levels(data_source$Survived) = c("No", "Yes")
  return(data_source)
}
```

### Decision trees
```{r}
data_source = load_data()
data_source$Name = NULL
data_source$Ticket = NULL
data_source$Cabin = NULL
data_source$PassengerId = NULL

titanic_tree = tree(Survived~., data=data_source)
summary(titanic_tree)
titanic_tree
plot(titanic_tree)
```
### Naive Bayes
```{r}
data_source = data.frame(read.csv("train.csv", header=T))
```

### kNN
```{r}
data_source = data.frame(read.csv("train.csv", header=T))
```

