---
title: "Data Mining - Clustering"
output: html_notebook
---
```{r}
install.packages('kohonen')
require(kohonen)
require(RColorBrewer)
```
## Data loading
```{r}
load_data = function() {
  data_source = data.frame(read.csv("./datasets/titanic.csv", header = T))
  library(varhandle)
  data_source$Sex = unfactor(data_source$Sex)
  data_source$Embarked = unfactor(data_source$Embarked)
  # Fill in missing age entries with average, embarked with Southampton
  for (i in 1:length(data_source$Age)) {
    if (is.na(data_source$Age[i])) {
      data_source$Age[i] = mean(data_source$Age, na.rm = TRUE)
    }
    
    if (data_source$Embarked[i] == "" ||
      data_source$Embarked[i] == "S") {
      data_source$Embarked[i] = 3
    }
    
    else if (data_source$Embarked[i] == "C") {
      data_source$Embarked[i] = 1
    }
    else if (data_source$Embarked[i] == "Q") {
      data_source$Embarked[i] = 2
    }
    
    if (data_source$Sex[i] == "male") {
      data_source$Sex[i] = 2
    }
    else if (data_source$Sex[i] == "female") {
      data_source$Sex[i] = 1
    }
  }
  data_source$Embarked = as.numeric(data_source$Embarked)
  data_source$Sex = as.numeric(data_source$Sex)
  
  data_source$Survived = as.factor(data_source$Survived)
  data_source$Pclass = as.factor(data_source$Pclass)
  data_source$Sex = as.factor(data_source$Sex)
  data_source$Embarked = as.factor(data_source$Embarked)
  levels(data_source$Embarked) = c("Southampton", "Cherbourg", "Queenstown", "Southampton")
  levels(data_source$Sex) = c("Female", "Male")
  levels(data_source$Survived) = c("No", "Yes")
  
  data_source$Family = data_source$Parch + data_source$SibSp
  data_source$SibSp = as.integer(data_source$SibSp)
  data_source$Parch = as.integer(data_source$Parch)
  data_source$Family = as.integer(data_source$Family)
  
  data_source$Embarked = as.numeric(data_source$Embarked)
  data_source$Sex = as.numeric(data_source$Sex)
  data_source$Pclass = as.numeric(data_source$Pclass)
  
  data_source$Ticket = NULL
  data_source$Name = NULL
  data_source$Cabin = NULL
  return(data_source)
}

```

## Algorithms

### SOM

```{r}
data = load_data()
#data$Survived = as.numeric(data$Survived)
data$Survived = NULL
data$PassengerId = NULL
som_original = som(as.matrix(data), grid = somgrid(15, 15, "hexagonal"))
som_scaled = som(scale(data), grid = somgrid(15, 15, "hexagonal"))
plot(som_original)
plot(som_original, type='changes')
plot(som_original, type='counts')
plot(som_scaled)
plot(som_scaled, type='changes')
plot(som_scaled, type='counts')
```


### EM

```{r}

em_algorithm = function(dataset, nr_clusters) {
  set.seed(1234)
  emobject = simple.init(dataset)
  emobject = shortemcluster(dataset, emobject)
  ret = emcluster(dataset, emobject, assign.class = TRUE)
  summary(emobject)
  #return(emobject)
}

em_algorithm(as.matrix(data), 2)
em_algorithm(scale(data), 2)


print(assign.class(scale(data), emobj = em_scaled))

install.packages('mclust')
library(mclust)
mcl = Mclust(data, G=2)

```































