---
title: "Data Mining - Clustering"
output: html_notebook
---

### Data loading
```{r}
preprocess_data = function(path){
  original = as.data.frame(read.table(path, header=F))
  labels = as.array(original[,ncol(original)])+1
  original[,ncol(original)] = NULL
  scaled = as.data.frame(scale(original))
  dataset = list(original=original, labels=labels, scaled=scaled)
  return(dataset)
}

```


### k-Means
```{r}
k_means = function(dataset, cluster_nr) {
  set.seed(20)
  kmeans_clusters = kmeans(dataset$scaled, cluster_nr)
  return(kmeans_clusters)
}

```

```{r}
install.packages("cluster")
suppressPackageStartupMessages(library(cluster))
```

```{r}
data = preprocess_data('datasets/2d-10c.dat')
<<<<<<< HEAD
silhouette_means = c()
wss_means = c()
for (k in 2:20) {
  kcl = k_means(data, k)
  clusters = kcl$cluster
  wss = kcl$withinss
  current_silhouette = silhouette(clusters, dist(data$original, method = "euclidean"))
  silhouette_means = c(silhouette_means, mean(current_silhouette[,3]))
  wss_means = c(wss_means, mean(wss))
}
plot(2:20, silhouette_means, type="l", ylim=c(0,0.6))
plot(2:20, wss_means, type="l")
          
#dist.res <- dist(data, method = "euclidean")
#hc <- hclust(dist.res, method = "complete")
#k.max <- 20
#sil <- rep(0, k.max)
=======

           
dist.res <- dist(as.vector(data$original), method = "euclidean")

sil = rep(0, 20)
for(i in 2:20){
  clusters =  k_means(data)
  ss = silhouette(clusters, dist(data$original))
  sil[i] = mean(ss[, 3])
}
plot(1:20, sil, type = "b", pch = 19, 
     frame = FALSE, xlab = "Number of clusters k")
abline(v = which.max(sil), lty = 2)




silhouette_score = function(k){
  km = k_means(data)
  ss = silhouette(data.frame(km),  dist(data$original))
  return(mean(ss[, 3]))
}
k=c(2,3,4,5,6)
avg_sil <- sapply(k, silhouette_score)

plot(k, type='b', avg_sil, xlab='Number of clusters', ylab='Average Silhouette Scores', frame=FALSE)
>>>>>>> ebcdddb1653f0651273189358dabca1f85cee459

```

